# Generated by Django 3.2.19 on 2023-07-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='phone_number',
            field=models.CharField(max_length=8),
        ),
    ]
